# Makefile generated by gb: http://go-gb.googlecode.com
# gb provides configuration-free building and distributing

include $(GOROOT)/src/Make.inc

TARG=github.com/droundy/gui
GOFILES=\
	helpers.go\
	interfaces.go\
	run.go\
	widgets.go\

# gb: this is the local install
GBROOT=.

# gb: compile/link against local install
GC+= -I $(GBROOT)/_obj
LD+= -L $(GBROOT)/_obj

package: $(GBROOT)/_obj/$(TARG).a

include $(GOROOT)/src/Make.pkg

# gb: local dependencies
_obj/$(TARG).a: $(GBROOT)/_obj/github.com/droundy/widgets/websocket.a
